version: "3.7"
services:
    app:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./:/app

    app-php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: app-db
            DB_USER: todo
            DB_PASSWORD: test
            DB_NAME: todo
        volumes:
            - ./:/app

    app-php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: app-db
            DB_USER: todo
            DB_PASSWORD: test
            DB_NAME: todo
        volumes:
            - ./:/app

    app-db:
        image: mariadb:10.5
        restart: always
        environment:
            MYSQL_DATABASE: todo
            MYSQL_USER: todo
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        volumes:
            - ./.database/postgres/data:/var/lib/mysql/data
        ports:
            - "33064:3306"
